name: CI

on: [ push ]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ 3.7, 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover tests
  versioning:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    needs: [ test ]

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Determine version tag
        id: versioning
        uses: codacy/git-version@2.4.0
        with:
          release-branch: main
          dev-branch: development
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install twine
      - name: Tag and build
        env:
          PACKAGE_VERSION: ${{ steps.versioning.outputs.version }}
        run: |
          sed s/version=.*/version=\"$PACKAGE_VERSION\",/ setup.py > new_setup.py
          mv new_setup.py setup.py
          cat setup.py
          python setup.py sdist
      - name: Create GitHub release
        id: github-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.versioning.outputs.version }}
          release_name: Release ${{ steps.versioning.outputs.version }}
          prerelease: ${{ github.ref == 'refs/heads/main' && 'false' || 'true' }}
      - name: Upload Github release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github-release.outputs.upload_url }}
          asset_path: dist/specc-${{ steps.versioning.outputs.version }}.tar.gz
          asset_name: specc-${{ steps.versioning.outputs.version }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload PyPI package
        if: github.ref == 'refs/heads/main'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
